FROM ubuntu:latest

RUN apt update && apt install -y \
    build-essential \
    libfcgi-dev \
    nginx \
    spawn-fcgi && \
    rm -rf /var/lib/apt/lists

RUN chmod 600 usr/bin/chsh && \
    chmod 600 usr/bin/chfn && \
    chmod 600 usr/bin/chage && \
    chmod 600 usr/bin/su && \
    chmod 600 usr/bin/passwd && \
    chmod 600 usr/bin/expiry && \
    chmod 600 usr/sbin/unix_chkpwd && \
    chmod 600 usr/sbin/pam_extrausers_chkpwd && \
    chmod 600 usr/bin/newgrp && \
    chmod 600 usr/bin/gpasswd && \
    chmod 600 usr/bin/wall && \
    chmod 600 usr/bin/umount && \
    chmod 600 usr/bin/mount && \     
    groupadd -r cont_group && \
    useradd -r -g cont_group cont_user

COPY server/server.c /app/server.c
COPY server/nginx/nginx.conf /etc/nginx/nginx.conf

RUN gcc -o server /app/server.c -lfcgi

USER coun_user

WORKDIR /app

CMD spawn-fcgi -a 127.0.0.1 -p 8080 -f ./server && nginx -g "daemon off;"

EXPOSE 8080

HEALTHCHECK --interval=5s --timeout=3s --retries=3 CMD [ "curl", "--fail", "http://localhost:81" ]'
