version: '3'

services:
  cont_server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - cont_network

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx_6part/nginx.conf:/etc/nginx/nginx.conf:rw
    depends_on:
      - cont_server
    restart: always
    networks:
      - cont_network

networks:
  cont_network:
    driver: bridge
